DROP TABLE Movie CASCADE CONSTRAINTS;
DROP TABLE Movie_Genre CASCADE CONSTRAINTS;
DROP TABLE Movie_Country CASCADE CONSTRAINTS;
DROP TABLE Cast CASCADE CONSTRAINTS;
DROP TABLE Tag CASCADE CONSTRAINTS;
DROP TABLE Movie_Director CASCADE CONSTRAINTS;
DROP TABLE Movie_Tag CASCADE CONSTRAINTS;

DROP INDEX  INDMOVIEID;
DROP INDEX  INDTAGID;
DROP INDEX  INDTAGVALUE;
